### ISSUE TITLE
Replace custom URI parsing standard package 

### ISSUE THREAD

**Issue by viyatb** [owtf/http-request-translator#60]
The custom URI parsing logic written in `hrt/url.py` should not be used (including the regexes). Instead a reliable parsing module like https://github.com/google/ipaddr-py should be used.

@DePierre ?

**Comment by DePierre** [comment]
@viyatb IIRC the main reason was to keep hrt as lightweight as possible so instead of having additional dependencies for such small code, we re-wrote it.

Is it really needed to have ipaddr-py as an additional dependency? It's 2000 lines of code for 100 lines for hrt. Sure it is much more tested, resilient to much more edge cases (I suppose) but does hrt need it?

**Comment by viyatb** [comment]
@DePierre https://github.com/owtf/http-request-translator/issues/59

**Comment by DePierre** [comment]
@viyatb I didn't say that ours was bug free haha.

Does it refute my remark though? 2000 LoC vs. < 100 LoC. Don't get me wrong, I am not against using a third-party. Bu if we do, I want to be convinced that it is out of necessity.

**Comment by viyatb** [comment]
@DePierre as long as its bug free, no problem! :)

**Comment by DePierre** [comment]
If it appears that more and more bugs are being reported due to our custom URL matching-thingy, and that in order to fix these bugs we have to write more codes (vs. fixing a typo for instance), we will seriously consider using third-party component. Until then, we'll test our custom code.

@viyatb Does it sound logical?

**Comment by viyatb** [comment]
@DePierre yes, sure.
