### ISSUE TITLE
Use requests for Python code translation.

### ISSUE THREAD

**Issue by viyatb** [owtf/http-request-translator#62]
Right now, HRT uses `pycurl` to transform the HTTP request to Python. It should use the more standard `requests` to do this.

**Comment by DePierre** [comment]
@viyatb The problem with `requests` is that, as you mentioned, it's standard. And we can't be sure if `requests` changed something in the request we were going to send. As @7a pointed out, the transformed request should be exactly what the user wanted to send, not automatically formatted one.

Let's say the user wants to check how the request behaves when sending a header `content-length : 42`. Using `requests`, you could be sending `Content-Length: 42`, which is different. Using `pycurl` we have more control about what we are sending.

Won't fix IMO but feel free to reopen if you have argument to discuss otherwise.
